environment:
  matrix:
    - PYTHON: "C:\\Python27\\python.exe"

    - PYTHON: "C:\\Python35\\python.exe"

install:
  - "devscripts\\appveyor_install.bat"

build_script:
  - "%PYTHON% run.py"

test_script:
  - chcp
  - chcp 65001
  - "%PYTHON% -m nose --verbose test"

on_finish:
  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
