environment:
  matrix:
    - PYTHON: "C:\\Python27\\python.exe"

    - PYTHON: "C:\\Python35\\python.exe"

install:
  - "devscripts\\appveyor_install.bat"

build_script:
  - "%PYTHON% run.py"

test_script:
  - "%PYTHON% -m nose --verbose test"
